import time
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from .utils import screen_clear

# Constants
REDIRECT_URI = 'http://localhost:8080'
SCOPE = 'playlist-modify-public playlist-modify-private user-library-read'

def liked_songs_to_playlist(client_id, client_secret, playlist_name="Liked Songs Playlist"):
    """Create a playlist and add all liked songs to it."""
    # Initialize Spotify client
    sp = spotipy.Spotify(auth_manager=SpotifyOAuth(
        client_id=client_id,
        client_secret=client_secret,
        redirect_uri=REDIRECT_URI,
        scope=SCOPE
    ))

    # Fetch user ID
    user_id = sp.current_user()["id"]

    # Create a new playlist
    try:
        print(f"Creating playlist '{playlist_name}'...")
        playlist = sp.user_playlist_create(
            user=user_id,
            name=playlist_name,
            public=False,
            description="Playlist generated by Likepotify containing all liked songs."
        )
        playlist_id = playlist["id"]
        print(f"Playlist created successfully: {playlist['name']}")
    except Exception as e:
        print(f"Error creating playlist: {e}")
        return

    # Fetch all liked songs
    liked_tracks = []
    offset = 0
    limit = 50

    print("Fetching liked songs...")
    while True:
        try:
            results = sp.current_user_saved_tracks(limit=limit, offset=offset)
            items = results.get("items", [])
            for item in items:
                track = item.get("track")
                if track:
                    liked_tracks.append(track["id"])
            if len(items) == 0:
                break
            offset += limit
        except Exception as e:
            print(f"Error fetching liked songs: {e}")
            return

    print(f"Total liked songs fetched: {len(liked_tracks)}")

    # Add liked songs to the playlist in batches of 100
    try:
        for i in range(0, len(liked_tracks), 100):
            sp.playlist_add_items(playlist_id, liked_tracks[i:i + 100])
            print(f"Added songs {i + 1} to {min(i + 100, len(liked_tracks))} to the playlist...")
    except Exception as e:
        print(f"Error adding songs to playlist: {e}")
        return

    print(f"All liked songs have been added to the playlist '{playlist_name}' successfully!")
    time.sleep(3)
    screen_clear()