import time
from colorama import Fore
from .utils import screen_clear, get_spotify_client


def liked_songs_to_playlist(client_id, client_secret, playlist_name="Liked Songs Playlist"):
    """Create a new playlist and copy all liked songs into it."""
    sp = get_spotify_client(client_id, client_secret)
    user_id = sp.current_user()["id"]

    # Create playlist
    try:
        print(Fore.CYAN + f"Creating playlist '{playlist_name}'...")
        playlist = sp.user_playlist_create(
            user=user_id,
            name=playlist_name,
            public=False,
            description="Generated by Likepotify — all your liked songs in one playlist.",
        )
        playlist_id = playlist["id"]
        print(Fore.GREEN + f"  Playlist created: {playlist['name']}")
    except Exception as e:
        print(Fore.RED + f"Error creating playlist: {e}")
        return

    # Fetch liked songs
    liked_tracks = []
    offset = 0
    limit = 50

    print(Fore.CYAN + "Fetching liked songs...")
    while True:
        try:
            results = sp.current_user_saved_tracks(limit=limit, offset=offset)
            items = results.get("items", [])
            if not items:
                break
            for item in items:
                track = item.get("track")
                if track and track.get("id"):
                    liked_tracks.append(track["id"])
            print(f"  Fetched {len(liked_tracks)} songs so far...")
            offset += limit
        except Exception as e:
            print(Fore.RED + f"Error fetching liked songs: {e}")
            return

    print(Fore.GREEN + f"Total liked songs: {len(liked_tracks)}")

    # Add in batches of 100 (Spotify API limit)
    try:
        for i in range(0, len(liked_tracks), 100):
            batch = liked_tracks[i : i + 100]
            sp.playlist_add_items(playlist_id, batch)
            print(f"  Added songs {i + 1}–{i + len(batch)}...")
    except Exception as e:
        print(Fore.RED + f"Error adding songs: {e}")
        return

    print(Fore.GREEN + f"\nAll {len(liked_tracks)} songs added to '{playlist_name}'!")
    time.sleep(2)
    screen_clear()
